### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by TransUMD** [TransUMD/Macroscopic-Fundamental-Diagram#1]
SUMO+MFD

**Comment by GuiRao** [comment]
Traceback (most recent call last):
File "SUMOSimulation.py", line 398, in
ChangeDemandRandom0()
File "SUMOSimulation.py", line 72, in ChangeDemandRandom0
for i in range(np.size(EdgeIn)):
NameError: name 'EdgeIn' is not defined

I don't know how to define these variables “EdgeIn, EdgeOut, NodeDemand” in SUMOSimulation.py.
