### ISSUE TITLE
a error when I run simulation

### ISSUE THREAD

**Issue by TwelveYC** [TransUMD/Macroscopic-Fundamental-Diagram#3]
> Traceback (most recent call last):  
  File "SUMOSimulation.py", line 398, in <module>  
    ChangeDemandRandom0()  
  File "SUMOSimulation.py", line 72, in ChangeDemandRandom0  
    for i in range(np.size(EdgeIn)):  
NameError: name 'EdgeIn' is not defined  

I don't know how to fix it.

**Comment by Angela945** [comment]
> > Traceback (most recent call last):
> > File "SUMOSimulation.py", line 398, in 
> > ChangeDemandRandom0()
> > File "SUMOSimulation.py", line 72, in ChangeDemandRandom0
> > for i in range(np.size(EdgeIn)):
> > NameError: name 'EdgeIn' is not defined
> 
> I don't know how to fix it.

It works if you define these variables “EdgeIn, EdgeOut, NodeDemand” in SUMOSimulation.py.
